openapi: "3.0.2"

info:
  title: Disciplines API
  version: "1.0"

servers:
  - url: http://localhost:8081
    description: local

paths:
  /discipline/{discipline-id}/labwork/{labwork-id}/add:
    post:
      description: |
        Add lab work to the discipline
      parameters:
        - $ref: '#/components/parameters/LabWorkIdPath'
        - $ref: '#/components/parameters/DisciplineIdPath'
      responses:
        '204':
          description: |
            Lab successfully added to discipline
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /discipline/{discipline-id}/labwork/{labwork-id}/remove:
    delete:
      description: |
        Remote lab work from the discipline
      parameters:
        - $ref: '#/components/parameters/LabWorkIdPath'
        - $ref: '#/components/parameters/DisciplineIdPath'
      responses:
        '204':
          description: |
            Lab successfully deleted from discipline
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  parameters:
    LabWorkIdPath:
      description: Unique identifier of lab work
      in: path
      name: labwork-id
      schema:
        type: integer
        format: int64
        minimum: 1
      required: true

    DisciplineIdPath:
      description: Unique identifier of discipline
      in: path
      name: discipline-id
      schema:
        type: integer
        format: int64
        minimum: 1
      required: true


  responses:
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: INTERNAL_SERVER_ERROR
              message:
                type: string
                example: Unable to process request
            required:
              - code
              - message

    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: ILLEGAL_ARGUMENT_PROVIDED
              message:
                type: string
                example: Identifier should be number
            required:
              - code
              - message

    '404':
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: LAB_NOT_FOUND
              message:
                type: string
                example: Lab with id=1 not found
            required:
              - code
              - message
